### ISSUE TITLE
Suggestion: Improve package discovery

### ISSUE THREAD

**Issue by sogko** [chris-ramon/graphql#7]
For discussion, how to improve discovery of this package

For a start, updating the repo description, at the very least, would help with other golang users/devs looking for a GraphQL package library for Golang,

Most of the golang community would google for Go related stuff by adding a `golang` keyword
(since `go` is a common keyword)

For e.g
Current repo description:
``` An implementation of GraphQL for Go```

Suggested repo description:
``` An implementation of GraphQL for Go / Golang```

For reference, other golang GraphQL libraries' description:
- https://github.com/cryptix/go-graphql : `GraphQL packages for golang`
- https://github.com/tmc/graphql : `graphql parser + utilities`
- https://github.com/sevki/graphql: `GraphQL implementation in go https://graphql.co`

For your consideration 😃

Btw: I've added this repo to this `awesome-graphql` list
- https://github.com/chentsulin/awesome-graphql#go-libraries

**Comment by chris-ramon** [comment]
Thanks for your consideration about this @sogko.

I had changed the package description to: `An implementation of GraphQL for Go / Golang`
Thanks a lot for adding it to `awesome-graphql` :star2: 

Also I've send a [pr](https://github.com/chris-ramon/awesome-go/pull/1) to add `graphql-go` to [awesome-go](https://github.com/avelino/awesome-go)

[godoc.org](http://godoc.org/?q=graphql) had already indexed the library some weeks ago :+1:

**Comment by sogko** [comment]
Awesome! 👍🏻 Let's hope more people pick up this library and contribute back!

I really want to see a Relay-compliant server in golang eventually coming out from this project.
Scala has a graphql implementation [`sangria-graphql`](http://sangria-graphql.org) with a library for Relay which seems to be really great.

**Comment by PeteJodo** [comment]
This seems to be the most active graphql implementation for go. I'm going to mess around with it a bit and hopefully be able to contribute back

**Comment by chris-ramon** [comment]
> This seems to be the most active graphql implementation for go. I'm going to mess around with it a bit and hopefully be able to contribute back

Thanks for taking the time if you do so! :star2:

**Comment by bsr203** [comment]
Hi, I played around with the js official version a bit and wonder how I can compare the go implementation with it. I saw @sogko's blog post and started exploring but please comment on feature parity with the js implementation or compliance with the spec. thanks for your work on this. bsr.

**Comment by chris-ramon** [comment]
> Hi, I played around with the js official version a bit and wonder how I can compare the go implementation with it. I saw @sogko's blog post and started exploring but please comment on feature parity with the js implementation or compliance with the spec. thanks for your work on this. bsr.

Hi @bsr203, you can think about this project as the `graphql-js` in Go plus all the great features Go provides.

The current state of the project is a working version as @sogko had shown on this [example](https://github.com/sogko/todomvc-relay-go), there are still some things to get done and improve, but I am confident we will have the first production ready version in the next weeks, planning myself using it on production.

**Comment by bsr203** [comment]
@chris-ramon thanks a ton for quick reply. I glimpsed through the source and it is quite easy for me to follow than js version. Thanks again for all your hard work and will comment on anything I come across. cheers.

**Comment by chris-ramon** [comment]
hehehe, glad to know that @bsr203 :+1: - thanks to @sogko, he had done enormous effort as well to reach the current state of the project :rocket:

**Comment by sogko** [comment]
No new updates, closed
